SELECT YEAR(DIFFERENTIATION_DATE) as YEAR,
    (MAX_SIZE - SIZE_OF_COLONY) as YEAR_DEV,
    ID
FROM ECOLI_DATA A
    JOIN (
    SELECT YEAR(DIFFERENTIATION_DATE) as YEAR,
    MAX(SIZE_OF_COLONY) as MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
    ) B ON YEAR(A.DIFFERENTIATION_DATE) = B.YEAR
ORDER BY YEAR, YEAR_DEV