WITH ReviewCount AS (
    SELECT MEMBER_ID, COUNT(*) as review_count
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY review_count DESC
    LIMIT 1
    )
SELECT
    m.MEMBER_NAME,
    r.REVIEW_TEXT,
    DATE_FORMAT(r.REVIEW_DATE, '%Y-%m-%d' )
FROM REST_REVIEW r
         JOIN MEMBER_PROFILE m ON r.MEMBER_ID = m.MEMBER_ID
WHERE r.MEMBER_ID = (SELECT MEMBER_ID FROM ReviewCount)
ORDER BY r.REVIEW_DATE ASC, r.REVIEW_TEXT ASC;


