SELECT H.FLAVOR #, JULY_TOTAL, H.TOTAL_ORDER
FROM FIRST_HALF H
         LEFT JOIN (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS JULY_TOTAL
    FROM JULY
    GROUP BY FLAVOR
) J ON H.FLAVOR = J.FLAVOR
ORDER BY (H.TOTAL_ORDER + J.JULY_TOTAL) DESC
    LIMIT 3